#------------------------------------------------------------------------------

SOURCE=lab1.cc
MYPROGRAM=simulator


CC=g++

#------------------------------------------------------------------------------



all: $(MYPROGRAM)



$(MYPROGRAM): $(SOURCE)

	$(CC) $(SOURCE) -o $(MYPROGRAM)

clean:
	rm -f *.d *.o *.out $(MYPROGRAM) *.class ImplType